spring:
  sql:
    init:
      mode: always
      platform: h2
      encoding: utf-8
      separator: ";"
      username: sa
      password: 123456
  datasource:
    url: jdbc:h2:mem:bdb;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
  jpa:
    database: h2
  mvc:
    servlet:
      path: /atm-simulator
  h2:
    console:
      enabled: true


